{
 "title": "CCR Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ccr_job_running_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccr_job_running_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job State",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "ccr_job_running_sync_state{instance=\"$instance\"}",
     "legendFormat": "SyncState"
    },
    {
     "expr": "ccr_job_running_sub_sync_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ccr_job_running_lag_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ccr_job_running_lag_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ccr_binlog_commit_seq{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binlogs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handle binlog QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "rate(ccr_handle_binlog_total{instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Handle binlog Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(name) (rate(ccr_handle_binlog_duration_seconds_sum{instance=\"$instance\"}[1m])) / sum by(name) (rate(ccr_handle_binlog_duration_seconds_count{instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, name) (rate(ccr_handle_binlog_duration_seconds_bucket{instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{name}}"
      }
     ]
    },
    {
     "title": "Binlog Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "ccr_job_running_lag_total{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Binlog Lag In Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "ccr_job_running_lag_seconds{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "QPS & Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Save Job Progress QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(ccr_job_progress_persist_total{instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Save Job Progress Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(name) (rate(ccr_job_progress_persist_duration_seconds_sum{instance=\"$instance\"}[1m])) / sum by(name) (rate(ccr_job_progress_persist_duration_seconds_count{instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, name) (rate(ccr_job_progress_persist_duration_seconds_bucket{instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{name}}"
      }
     ]
    },
    {
     "title": "SQL EXEC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(host) (rate(ccr_sql_exec_total{instance=\"$instance\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL EXEC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(host) (rate(ccr_sql_exec_duration_seconds_sum{instance=\"$instance\"}[1m])) / sum by(host) (rate(ccr_sql_exec_duration_seconds_count{instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{host}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, host) (rate(ccr_sql_exec_duration_seconds_bucket{instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{host}}"
      }
     ]
    },
    {
     "title": "FE RPC QPS - Txn",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(ccr_fe_rpc_total{method=\"BeginTransaction\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(ccr_fe_rpc_total{method=\"CommitTransaction\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FE RPC Latency - Txn",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_fe_rpc_duration_seconds_bucket{method=\"BeginTransaction\", instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_fe_rpc_duration_seconds_bucket{method=\"CommitTransaction\", instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      },
      {
       "expr": "sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_sum{method=\"BeginTransaction\", instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_count{method=\"BeginTransaction\", instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      },
      {
       "expr": "sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_sum{method=\"CommitTransaction\", instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_count{method=\"CommitTransaction\", instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      }
     ]
    },
    {
     "title": "FE RPC QPS - Meta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(ccr_fe_rpc_total{method=\"GetDbMeta\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(ccr_fe_rpc_total{method=\"GetBackends\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(ccr_fe_rpc_total{method=\"GetTableMeta\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FE RPC Latency - Meta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_fe_rpc_duration_seconds_bucket{method=\"GetDbMeta\", instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      },
      {
       "expr": "sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_sum{method=\"GetDbMeta\", instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_count{method=\"GetDbMeta\", instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_fe_rpc_duration_seconds_bucket{method=\"GetTableMeta\", instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_fe_rpc_duration_seconds_bucket{method=\"GetBackends\", instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      },
      {
       "expr": "sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_sum{method=\"GetTableMeta\", instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_count{method=\"GetTableMeta\", instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      },
      {
       "expr": "sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_sum{method=\"GetBackends\", instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_count{method=\"GetBackends\", instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      }
     ]
    },
    {
     "title": "FE RPC QPS - GetBinlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(ccr_fe_rpc_total{method=\"GetBinlog\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FE RPC Latency - GetBinlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_fe_rpc_duration_seconds_bucket{method=\"GetBinlog\", instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      },
      {
       "expr": "sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_sum{method=\"GetBinlog\", instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_fe_rpc_duration_seconds_count{method=\"GetBinlog\", instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      }
     ]
    },
    {
     "title": "BE RPC QPS - IngestBinlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(ccr_be_rpc_total{method=\"IngestBinlog\", instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BE RPC Latency - IngestBinlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(method, addr) (rate(ccr_be_rpc_duration_seconds_sum{instance=\"$instance\"}[1m])) / sum by(method, addr) (rate(ccr_be_rpc_duration_seconds_count{instance=\"$instance\"}[1m]))",
       "legendFormat": "AVG {{method}} - {{addr}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, method, addr) (rate(ccr_be_rpc_duration_seconds_bucket{instance=\"$instance\"}[1m])))",
       "legendFormat": "P99 {{method}} - {{addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cumulative error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "ccr_error_total{instance=\"$instance\"}",
       "legendFormat": "{{error}} - {{type}}"
      }
     ]
    }
   ]
  }
 ]
}