// Code generated by Kitex v0.8.0. DO NOT EDIT.
package heartbeatservice

import (
	server "github.com/cloudwego/kitex/server"
	heartbeatservice "github.com/selectdb/ccr_syncer/pkg/rpc/kitex_gen/heartbeatservice"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler heartbeatservice.HeartbeatService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
